remote_theme: just-the-docs/just-the-docs
title: El Zoominario
logo: /assets/pics/logo.png
title_only_logo: false
exclude:
   - README.md
aux_links:
  "Materials on GitHub":
    - "//github.com/solislemuslab/el-zoominario"
footer_content: "Copyright Solis-Lemus lab &copy; 2024. Distributed by an <a href=\"https://github.com/solislemuslab/el-zoominario/blob/master/LICENSE\">MIT license.</a>"
callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red
compress_html:
  blanklines: true
# LaTeX rendering via "katex" (KaTeX, default) or "mathjax" (MathJax) or "none" / "off" (NO rendering)
# https://github.com/just-the-docs/just-the-docs/issues/198
latex: katex